TSIS2.WebResources/Webresources/html/SurveyCreator.html, TSIS2.WebResources/Webresources/html/SurveyRender.html
Fix a mistmatch in font-size in the row and column text in the matrix question type in SurveyJS
See item #68000 comment in DevOps.
=> Added missing DOCTYPE declarations

TSIS2.WebResources/Webresources/js/surveycreator.js
=> Reordered toolbox items

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/js/WorkOrderServiceTaskRibbon.js, TSIS2.WebResources/spkl.json
I have unfinished work in the Work Order Service Task Ribbon that depend on this script right now. Hamza needs to push his ribbon changes to QA, so I hid my unfinished work, and I'm adding this in so there aren't any dependency issues when moving to QA.
=> Added WorkOrderServiceTaskRibbon.js

TSIS2.WebResources/Webresources/js/WorkOrderServiceTaskRibbon.js
I must have not cleared my cache or somethin because the refactor was bad, due to roles not being an array, so not having the every() function.
=> isROMRole refactor fix

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts
PBI 81111 Filtering Country based on active Operations and Sites
=> Remove created on from Operation Type lookup display

TSIS2.WebResources/Webresources/js/WorkOrderRibbon.js
This reverts commit 35860af35d20f47b53aba3d1c6dd35df05aff24e.
=> Revert "Updated statuscode for closed WO service tasks"

TSIS2.WebResources/Webresources/html/SurveyCreator.html, TSIS2.WebResources/Webresources/js/buildprovisiontext.js, TSIS2.WebResources/Webresources/js/tsis2findingwidget.js
tsis2findingwidget.js uses buildprovisiontext.js functions
=> refactored buildProvisionText(), 

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts
Fix bug where country doesn't unlock if user fills out WO type and then region
=> Fix bug where country doesn't unlock (WO form)

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts
PBI 85342
New WO - Stakeholder error / Nouvelle ordre de travail/ validation pour stakeholder est en place automatiquement
=> Remove lock on service account on new WO form

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/js/QuestionnaireVersion.js, TSIS2.WebResources/Webresources/resx/QuestionnaireVersion.1033.Designer.cs, TSIS2.WebResources/Webresources/resx/QuestionnaireVersion.1033.resx, TSIS2.WebResources/Webresources/resx/QuestionnaireVersion.1036.Designer.cs, TSIS2.WebResources/Webresources/resx/QuestionnaireVersion.1036.resx, TSIS2.WebResources/src/ts/QuestionnaireVersion.ts
Also added check that start date should be before end date
=> Effective Dates can not be in range of other Questionnaire Version

TSIS2.WebResources/Webresources/js/Finding.js, TSIS2.WebResources/src/ts/Finding.ts
to make sure that all fields are locked when finding is marked complete
=> Moved disabledFormFields 

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/html/RATEFactor1Guide.html, TSIS2.WebResources/Webresources/html/RATEFactor1GuidePopUp.html, TSIS2.WebResources/Webresources/html/RATEFactor2Guide.html, TSIS2.WebResources/Webresources/html/RATEFactor2GuidePopUp.html, TSIS2.WebResources/Webresources/html/RATEFactor3Guide.html, TSIS2.WebResources/Webresources/html/RATEFactor3GuidePopUp.html, TSIS2.WebResources/Webresources/html/RATEFactor4Guide.html, TSIS2.WebResources/Webresources/html/RATEFactor4GuidePopUp.html, TSIS2.WebResources/spkl.json
Initial web resources and setup for each factor.  Guide consists of a  button that calls the modal pop up which is in the Guide Pop Up.
=> PBI: 165311

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/js/Common.js, TSIS2.WebResources/spkl.json
Create new common JavaScript file. This file contains common methods
[AB#171321](https://dev.azure.com/transport-canada/4898e801-ec08-49fb-b968-03e03a3d7c7f/_workitems/edit/171321)
=> PBI: 171321

TSIS2.WebResources/Webresources/js/buildprovisiontext.js
Made code changes to fix defect [AB#173069](https://dev.azure.com/transport-canada/4898e801-ec08-49fb-b968-03e03a3d7c7f/_workitems/edit/173069)
=> Fixed defect 173069 PAX Legs - Formatting issues

TSIS2.WebResources/Webresources/js/WorkOrder.js
[AB#168941](https://dev.azure.com/transport-canada/4898e801-ec08-49fb-b968-03e03a3d7c7f/_workitems/edit/168941)
=> Removed one work location option from WO main form. 

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/html/EmailAttachFile.html, TSIS2.WebResources/Webresources/html/EmailAttachFilePopUp.html, TSIS2.WebResources/spkl.json
A web resource that allows users to only attach files to emails that only reside in the Files table.
Currently a work in progress.
=> 168205 attach document centre files to email

TSIS2.WebResources/Webresources/css/survey.min.css
=> Change survey mandatory questions title in black 

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts
Updated logic for calculating TC quarter
=> PBI AB#167906

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts, TSIS2.WebResources/typings/XRM/Form/msdyn_workorder/Main/ROMOversightActivity.d.ts, TSIS2.WebResources/typings/XRM/Form/ovs_operation/Main/Information.d.ts, TSIS2.WebResources/typings/XRM/Web/ovs_operation.d.ts
=> AB#148532 cant complete wo - work in progress

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/js/TripRibbon.js, TSIS2.WebResources/spkl.json
[AB#148763](https://dev.azure.com/transport-canada/4898e801-ec08-49fb-b968-03e03a3d7c7f/_workitems/edit/148763) - The ability to book an inspection / La possibilité de réserver une inspection
=> Added TripRibbon js file

TSIS2.WebResources/Webresources/js/WorkOrderRibbon.js, TSIS2.WebResources/Webresources/resx/WorkOrder.1033.Designer.cs, TSIS2.WebResources/Webresources/resx/WorkOrder.1033.resx, TSIS2.WebResources/Webresources/resx/WorkOrder.1036.Designer.cs, TSIS2.WebResources/Webresources/resx/WorkOrder.1036.resx
The ability to book an inspection enhancement
=> PBI AB#148763 enhancement

TSIS2.WebResources/Webresources/html/ProvisionRender.html, TSIS2.WebResources/Webresources/js/WorkOrderServiceTask.js, TSIS2.WebResources/src/ts/WorkOrderServiceTask.ts
Mechanism for programs to control visibility of Oversight Details and service provider fields visibility
=> PBI AB#245973

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts, TSIS2.WebResources/typings/XRM/Web/teammembership.d.ts, TSIS2.WebResources/typings/XRM/_internal/web-entities.d.ts
=> AB#254624 work order status

TSIS2.WebResources/TSIS2.WebResources.csproj, TSIS2.WebResources/Webresources/js/Action.js, TSIS2.WebResources/src/ts/Action.ts
Actions Status -> Delivered/Requested/Received/Referred Form Field Set
Actions Status -> Convened/Consulted Form Field Set
=> PBI AB#267119 & AB#267140

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts
Trips - grouping time tracking
=> PBI AB#282334

TSIS2.WebResources/Webresources/js/Plan.js, TSIS2.WebResources/Webresources/js/PlanRibbon.js, TSIS2.WebResources/src/ts/Plan.ts
=> Planning summary fields AB#290490 AB#290489

TSIS2.WebResources/Webresources/js/WorkOrderServiceTask.js, TSIS2.WebResources/src/ts/WorkOrderServiceTask.ts
Locking of the "Mandatory" field in the Summary tab of the Service Task
=> PBI AB#294571

TSIS2.WebResources/Webresources/js/PlanRibbon.js
Fixed "Estimated Travel Time" calculation issue as well
=> PBI AB#306868 - Implementing supporting region in planning

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts, TSIS2.WebResources/typings/XRM/Form/msdyn_workorder/Main/ROMOversightActivity.d.ts
https://dev.azure.com/transport-canada/ROM/_workitems/edit/336706/
=> 336706 fix undefined operation in WO

TSIS2.WebResources/Webresources/js/FunctionalLocation.js, TSIS2.WebResources/Webresources/js/Operation.js, TSIS2.WebResources/src/ts/FunctionalLocation.ts, TSIS2.WebResources/src/ts/Operation.ts
=> 148730: Offline Code

TSIS2.WebResources/Webresources/js/WorkOrder.js, TSIS2.WebResources/src/ts/WorkOrder.ts, TSIS2.WebResources/typings/XRM/Form/msdyn_workorder/Main/ROM20.d.ts, TSIS2.WebResources/typings/XRM/Form/msdyn_workorder/Main/ROMOversightActivity.d.ts
"Work Order" - "Workspace" tab updates
=> PBI AB#350265

TSIS2.WebResources/Webresources/js/Plan.js, TSIS2.WebResources/src/ts/Plan.ts
Lock justification column under Site Inspection (OPM) when plan status is complete or HQreview
=> Lock justification column under Site Inspection (OPM) 

TSIS2.WebResources/Webresources/js/PlanRibbon.js
Supporting inspection- counting in plan
=> PBI AB#406842

TSIS2.WebResources/Webresources/js/PlanRibbon.js
=> PBI AB#404124

TSIS2.WebResources/Webresources/js/OperationRiskAssessment.js, TSIS2.WebResources/Webresources/js/OperationRiskAssessmentRibbon.js, TSIS2.WebResources/spkl.json, TSIS2.WebResources/src/ts/OperationRiskAssessment.ts
- Add setRiskThreshold function to fetch matching risk category (threshold)
- Set threshold values when risk score changes
- Support both English and French thresholds
=> Fill risk threshold on operation risk assessment

TSIS2.WebResources/Webresources/js/QuestionnaireResponse.js, TSIS2.WebResources/src/ts/QuestionnaireResponse.ts
Added console log for offline mode loading and improved handling of questionnaire responses by setting them to null if empty or undefined.
=> AB#435174 Enhance QuestionnaireResponse with debugging and error checks

TSIS2.WebResources/Webresources/html/SharePointAttachFilePopUp.html
=> Store Uploaded Files in Correct SharePoint Subfolder Using Unique Fol… AB#444193
